services:
  ai-service:
    # build:
    #   context: ./ai-service
    # image: ai-service:latest
    image: ghcr.io/king133444/ai-service
    environment:
      # 可在运行前通过导出/前缀传入，如：PORT=3001 AI_SERVICE_API_KEY=... docker compose up -d
      PORT: ${PORT:-3001}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000,http://localhost:3001,http://localhost:8000,http://10.10.218.18:8000}
      AI_SERVICE_API_KEY: ${AI_SERVICE_API_KEY:-}
      PROVIDER: ${PROVIDER:-qwen}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY:-}
      DEEPSEEK_BASE_URL: ${DEEPSEEK_BASE_URL:-https://api.deepseek.com}
      DEEPSEEK_MODEL: ${DEEPSEEK_MODEL:-deepseek-chat}
      QWEN_API_KEY: ${QWEN_API_KEY:-}
      QWEN_BASE_URL: ${QWEN_BASE_URL:-https://dashscope.aliyuncs.com/compatible-mode/v1}
      QWEN_MODEL: ${QWEN_MODEL:-qwen-flash}
      OLLAMA_API_KEY: ${OLLAMA_API_KEY:-}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://host.docker.internal:11434/v1}
      OLLAMA_MODEL: ${OLLAMA_MODEL:-llama3.1}
    ports:
      - "3001:3001"
    restart: unless-stopped

