name: Build and Publish AI Service (multi-arch)

on:
  push:
    branches: [ main ]
    paths:
      - 'ai-service/**'
      - '.github/workflows/ai-service-docker.yml'
    tags:
      - 'ai-service-v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (emulation)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/ai-service
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=ref,event=tag

      - name: Build and push (linux/amd64, linux/arm64)
        uses: docker/build-push-action@v6
        with:
          context: ./ai-service
          file: ./ai-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 可选：同时推送到 Docker Hub（设置 DOCKERHUB_USERNAME/DOCKERHUB_TOKEN 机密）
      # - name: Login to Docker Hub
      #   if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # - name: Build and push to Docker Hub
      #   if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./ai-service
      #     file: ./ai-service/Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-service:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max


